<a href="https://colab.research.google.com/github/Skkuhodomo/private_LLM/blob/main/3_Pytorch%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 65, -33, -11, -70, -14,  -5])

In [ ]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [ ]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones= torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
input = torch.empty(2,3)
input

tensor([[-2.5499e-14,  4.3960e-41, -2.5499e-14],
        [ 4.3960e-41,  4.4842e-44,  0.0000e+00]])

In [ ]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [ ]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [ ]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [ ]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[    134740252667280,     134740252667280, 8440344085702995297],
        [2478507435169572211, 7598543875864666156, 4049618011745840751]])

# 선형 변환
nn.Linear(입력 차원, 출력차원, 편향 여부)


In [1]:
import torch.nn as nn
import torch
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear( 3, 3, bias = False)
print(sample)
print(linear(sample))

tensor([10., 10., 10.])
tensor([9.1607, 5.0730, 0.3408], grad_fn=<SqueezeBackward4>)
